apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    remoteManifests:
      - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: fahad3611/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src:
            dest:
